/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.myDsl.Expression;
import org.xtext.example.mydsl.myDsl.IfExpression;
import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.OperationExpression;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>If Expression</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.IfExpressionImpl#getIfcondition <em>Ifcondition</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.IfExpressionImpl#getIfbody <em>Ifbody</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.IfExpressionImpl#getElsecondition <em>Elsecondition</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.IfExpressionImpl#getElseifbody <em>Elseifbody</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.IfExpressionImpl#getElsebody <em>Elsebody</em>}</li>
 * </ul>
 *
 * @generated
 */
public class IfExpressionImpl extends ExpressionImpl implements IfExpression
{
  /**
   * The cached value of the '{@link #getIfcondition() <em>Ifcondition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIfcondition()
   * @generated
   * @ordered
   */
  protected OperationExpression ifcondition;

  /**
   * The cached value of the '{@link #getIfbody() <em>Ifbody</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIfbody()
   * @generated
   * @ordered
   */
  protected EList<EObject> ifbody;

  /**
   * The cached value of the '{@link #getElsecondition() <em>Elsecondition</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getElsecondition()
   * @generated
   * @ordered
   */
  protected EList<OperationExpression> elsecondition;

  /**
   * The cached value of the '{@link #getElseifbody() <em>Elseifbody</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getElseifbody()
   * @generated
   * @ordered
   */
  protected EList<EObject> elseifbody;

  /**
   * The cached value of the '{@link #getElsebody() <em>Elsebody</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getElsebody()
   * @generated
   * @ordered
   */
  protected EList<Expression> elsebody;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IfExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.IF_EXPRESSION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OperationExpression getIfcondition()
  {
    return ifcondition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetIfcondition(OperationExpression newIfcondition, NotificationChain msgs)
  {
    OperationExpression oldIfcondition = ifcondition;
    ifcondition = newIfcondition;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.IF_EXPRESSION__IFCONDITION, oldIfcondition, newIfcondition);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIfcondition(OperationExpression newIfcondition)
  {
    if (newIfcondition != ifcondition)
    {
      NotificationChain msgs = null;
      if (ifcondition != null)
        msgs = ((InternalEObject)ifcondition).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.IF_EXPRESSION__IFCONDITION, null, msgs);
      if (newIfcondition != null)
        msgs = ((InternalEObject)newIfcondition).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.IF_EXPRESSION__IFCONDITION, null, msgs);
      msgs = basicSetIfcondition(newIfcondition, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.IF_EXPRESSION__IFCONDITION, newIfcondition, newIfcondition));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<EObject> getIfbody()
  {
    if (ifbody == null)
    {
      ifbody = new EObjectContainmentEList<EObject>(EObject.class, this, MyDslPackage.IF_EXPRESSION__IFBODY);
    }
    return ifbody;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<OperationExpression> getElsecondition()
  {
    if (elsecondition == null)
    {
      elsecondition = new EObjectContainmentEList<OperationExpression>(OperationExpression.class, this, MyDslPackage.IF_EXPRESSION__ELSECONDITION);
    }
    return elsecondition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<EObject> getElseifbody()
  {
    if (elseifbody == null)
    {
      elseifbody = new EObjectContainmentEList<EObject>(EObject.class, this, MyDslPackage.IF_EXPRESSION__ELSEIFBODY);
    }
    return elseifbody;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Expression> getElsebody()
  {
    if (elsebody == null)
    {
      elsebody = new EObjectContainmentEList<Expression>(Expression.class, this, MyDslPackage.IF_EXPRESSION__ELSEBODY);
    }
    return elsebody;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.IF_EXPRESSION__IFCONDITION:
        return basicSetIfcondition(null, msgs);
      case MyDslPackage.IF_EXPRESSION__IFBODY:
        return ((InternalEList<?>)getIfbody()).basicRemove(otherEnd, msgs);
      case MyDslPackage.IF_EXPRESSION__ELSECONDITION:
        return ((InternalEList<?>)getElsecondition()).basicRemove(otherEnd, msgs);
      case MyDslPackage.IF_EXPRESSION__ELSEIFBODY:
        return ((InternalEList<?>)getElseifbody()).basicRemove(otherEnd, msgs);
      case MyDslPackage.IF_EXPRESSION__ELSEBODY:
        return ((InternalEList<?>)getElsebody()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.IF_EXPRESSION__IFCONDITION:
        return getIfcondition();
      case MyDslPackage.IF_EXPRESSION__IFBODY:
        return getIfbody();
      case MyDslPackage.IF_EXPRESSION__ELSECONDITION:
        return getElsecondition();
      case MyDslPackage.IF_EXPRESSION__ELSEIFBODY:
        return getElseifbody();
      case MyDslPackage.IF_EXPRESSION__ELSEBODY:
        return getElsebody();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.IF_EXPRESSION__IFCONDITION:
        setIfcondition((OperationExpression)newValue);
        return;
      case MyDslPackage.IF_EXPRESSION__IFBODY:
        getIfbody().clear();
        getIfbody().addAll((Collection<? extends EObject>)newValue);
        return;
      case MyDslPackage.IF_EXPRESSION__ELSECONDITION:
        getElsecondition().clear();
        getElsecondition().addAll((Collection<? extends OperationExpression>)newValue);
        return;
      case MyDslPackage.IF_EXPRESSION__ELSEIFBODY:
        getElseifbody().clear();
        getElseifbody().addAll((Collection<? extends EObject>)newValue);
        return;
      case MyDslPackage.IF_EXPRESSION__ELSEBODY:
        getElsebody().clear();
        getElsebody().addAll((Collection<? extends Expression>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.IF_EXPRESSION__IFCONDITION:
        setIfcondition((OperationExpression)null);
        return;
      case MyDslPackage.IF_EXPRESSION__IFBODY:
        getIfbody().clear();
        return;
      case MyDslPackage.IF_EXPRESSION__ELSECONDITION:
        getElsecondition().clear();
        return;
      case MyDslPackage.IF_EXPRESSION__ELSEIFBODY:
        getElseifbody().clear();
        return;
      case MyDslPackage.IF_EXPRESSION__ELSEBODY:
        getElsebody().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.IF_EXPRESSION__IFCONDITION:
        return ifcondition != null;
      case MyDslPackage.IF_EXPRESSION__IFBODY:
        return ifbody != null && !ifbody.isEmpty();
      case MyDslPackage.IF_EXPRESSION__ELSECONDITION:
        return elsecondition != null && !elsecondition.isEmpty();
      case MyDslPackage.IF_EXPRESSION__ELSEIFBODY:
        return elseifbody != null && !elseifbody.isEmpty();
      case MyDslPackage.IF_EXPRESSION__ELSEBODY:
        return elsebody != null && !elsebody.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //IfExpressionImpl
