/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.OperationExpression;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Operation Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class OperationExpressionImpl extends BlockExpressionsImpl implements OperationExpression
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OperationExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.OPERATION_EXPRESSION;
  }

} //OperationExpressionImpl
