/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.InkAppImpl <em>Ink App</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.InkAppImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getInkApp()
   * @generated
   */
  int INK_APP = 0;

  /**
   * The feature id for the '<em><b>Globals</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INK_APP__GLOBALS = 0;

  /**
   * The feature id for the '<em><b>Tasks</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INK_APP__TASKS = 1;

  /**
   * The feature id for the '<em><b>Entry</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INK_APP__ENTRY = 2;

  /**
   * The number of structural features of the '<em>Ink App</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INK_APP_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.BreakImpl <em>Break</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.BreakImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getBreak()
   * @generated
   */
  int BREAK = 1;

  /**
   * The feature id for the '<em><b>Break</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BREAK__BREAK = 0;

  /**
   * The number of structural features of the '<em>Break</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BREAK_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.VariableTypeImpl <em>Variable Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.VariableTypeImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getVariableType()
   * @generated
   */
  int VARIABLE_TYPE = 2;

  /**
   * The number of structural features of the '<em>Variable Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_TYPE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.GlobalVariableImpl <em>Global Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.GlobalVariableImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getGlobalVariable()
   * @generated
   */
  int GLOBAL_VARIABLE = 3;

  /**
   * The feature id for the '<em><b>Variable</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GLOBAL_VARIABLE__VARIABLE = 0;

  /**
   * The number of structural features of the '<em>Global Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GLOBAL_VARIABLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.MainImpl <em>Main</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.MainImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getMain()
   * @generated
   */
  int MAIN = 4;

  /**
   * The feature id for the '<em><b>Variable Declerations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN__VARIABLE_DECLERATIONS = 0;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN__BODY = 1;

  /**
   * The number of structural features of the '<em>Main</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.FunctionBodyImpl <em>Function Body</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.FunctionBodyImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFunctionBody()
   * @generated
   */
  int FUNCTION_BODY = 5;

  /**
   * The feature id for the '<em><b>Variable Declerations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_BODY__VARIABLE_DECLERATIONS = 0;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_BODY__BODY = 1;

  /**
   * The number of structural features of the '<em>Function Body</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_BODY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.EntryTaskImpl <em>Entry Task</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.EntryTaskImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getEntryTask()
   * @generated
   */
  int ENTRY_TASK = 6;

  /**
   * The feature id for the '<em><b>Task</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTRY_TASK__TASK = 0;

  /**
   * The number of structural features of the '<em>Entry Task</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTRY_TASK_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.TaskImpl <em>Task</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.TaskImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getTask()
   * @generated
   */
  int TASK = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__NAME = 0;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__BODY = 1;

  /**
   * The feature id for the '<em><b>Task</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__TASK = 2;

  /**
   * The number of structural features of the '<em>Task</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ExpressionImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 11;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.IfExpressionImpl <em>If Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.IfExpressionImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getIfExpression()
   * @generated
   */
  int IF_EXPRESSION = 8;

  /**
   * The feature id for the '<em><b>Ifcondition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_EXPRESSION__IFCONDITION = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Ifbody</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_EXPRESSION__IFBODY = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Elsecondition</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_EXPRESSION__ELSECONDITION = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Elseifbody</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_EXPRESSION__ELSEIFBODY = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Elsebody</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_EXPRESSION__ELSEBODY = EXPRESSION_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>If Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ForExpressionImpl <em>For Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ForExpressionImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getForExpression()
   * @generated
   */
  int FOR_EXPRESSION = 9;

  /**
   * The feature id for the '<em><b>Initial</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_EXPRESSION__INITIAL = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Test</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_EXPRESSION__TEST = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Update</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_EXPRESSION__UPDATE = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_EXPRESSION__BODY = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>For Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.WhileExpressionImpl <em>While Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.WhileExpressionImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getWhileExpression()
   * @generated
   */
  int WHILE_EXPRESSION = 10;

  /**
   * The feature id for the '<em><b>Test</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE_EXPRESSION__TEST = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE_EXPRESSION__BODY = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>While Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.OperationExpressionImpl <em>Operation Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.OperationExpressionImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getOperationExpression()
   * @generated
   */
  int OPERATION_EXPRESSION = 12;

  /**
   * The number of structural features of the '<em>Operation Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ArrayDimensionImpl <em>Array Dimension</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ArrayDimensionImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getArrayDimension()
   * @generated
   */
  int ARRAY_DIMENSION = 13;

  /**
   * The feature id for the '<em><b>Index</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_DIMENSION__INDEX = 0;

  /**
   * The feature id for the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_DIMENSION__SIZE = 1;

  /**
   * The number of structural features of the '<em>Array Dimension</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_DIMENSION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.VariableSymbolImpl <em>Variable Symbol</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.VariableSymbolImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getVariableSymbol()
   * @generated
   */
  int VARIABLE_SYMBOL = 16;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_SYMBOL__TYPE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_SYMBOL__NAME = 1;

  /**
   * The number of structural features of the '<em>Variable Symbol</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_SYMBOL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.VariableDeclerationImpl <em>Variable Decleration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.VariableDeclerationImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getVariableDecleration()
   * @generated
   */
  int VARIABLE_DECLERATION = 14;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLERATION__TYPE = VARIABLE_SYMBOL__TYPE;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLERATION__NAME = VARIABLE_SYMBOL__NAME;

  /**
   * The feature id for the '<em><b>Dimension</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLERATION__DIMENSION = VARIABLE_SYMBOL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Variable Decleration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLERATION_FEATURE_COUNT = VARIABLE_SYMBOL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.FunctionParameterImpl <em>Function Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.FunctionParameterImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFunctionParameter()
   * @generated
   */
  int FUNCTION_PARAMETER = 15;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_PARAMETER__TYPE = VARIABLE_SYMBOL__TYPE;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_PARAMETER__NAME = VARIABLE_SYMBOL__NAME;

  /**
   * The number of structural features of the '<em>Function Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_PARAMETER_FEATURE_COUNT = VARIABLE_SYMBOL_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.AtomicImpl <em>Atomic</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.AtomicImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAtomic()
   * @generated
   */
  int ATOMIC = 17;

  /**
   * The number of structural features of the '<em>Atomic</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATOMIC_FEATURE_COUNT = OPERATION_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.VariableReturnImpl <em>Variable Return</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.VariableReturnImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getVariableReturn()
   * @generated
   */
  int VARIABLE_RETURN = 18;

  /**
   * The feature id for the '<em><b>Return</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_RETURN__RETURN = 0;

  /**
   * The number of structural features of the '<em>Variable Return</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_RETURN_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.AtomicOrFunctionCallImpl <em>Atomic Or Function Call</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.AtomicOrFunctionCallImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAtomicOrFunctionCall()
   * @generated
   */
  int ATOMIC_OR_FUNCTION_CALL = 19;

  /**
   * The number of structural features of the '<em>Atomic Or Function Call</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATOMIC_OR_FUNCTION_CALL_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.FunctionDefinitionImpl <em>Function Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.FunctionDefinitionImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFunctionDefinition()
   * @generated
   */
  int FUNCTION_DEFINITION = 20;

  /**
   * The feature id for the '<em><b>Return</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_DEFINITION__RETURN = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_DEFINITION__NAME = 1;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_DEFINITION__PARAMETERS = 2;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_DEFINITION__BODY = 3;

  /**
   * The number of structural features of the '<em>Function Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_DEFINITION_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.AbstractFunctionCallImpl <em>Abstract Function Call</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.AbstractFunctionCallImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAbstractFunctionCall()
   * @generated
   */
  int ABSTRACT_FUNCTION_CALL = 23;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_FUNCTION_CALL__PARAMETERS = ATOMIC_OR_FUNCTION_CALL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Abstract Function Call</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_FUNCTION_CALL_FEATURE_COUNT = ATOMIC_OR_FUNCTION_CALL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.FunctionCallImpl <em>Function Call</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.FunctionCallImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFunctionCall()
   * @generated
   */
  int FUNCTION_CALL = 21;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_CALL__PARAMETERS = ABSTRACT_FUNCTION_CALL__PARAMETERS;

  /**
   * The feature id for the '<em><b>Function</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_CALL__FUNCTION = ABSTRACT_FUNCTION_CALL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Function Call</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_CALL_FEATURE_COUNT = ABSTRACT_FUNCTION_CALL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.BuiltinFunctionCallImpl <em>Builtin Function Call</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.BuiltinFunctionCallImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getBuiltinFunctionCall()
   * @generated
   */
  int BUILTIN_FUNCTION_CALL = 22;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUILTIN_FUNCTION_CALL__PARAMETERS = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Function</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUILTIN_FUNCTION_CALL__FUNCTION = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Builtin Function Call</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUILTIN_FUNCTION_CALL_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.OperationImpl <em>Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.OperationImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getOperation()
   * @generated
   */
  int OPERATION = 24;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__LEFT = OPERATION_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__OPERATOR = OPERATION_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__RIGHT = OPERATION_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_FEATURE_COUNT = OPERATION_EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.IntegerReferenceImpl <em>Integer Reference</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.IntegerReferenceImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getIntegerReference()
   * @generated
   */
  int INTEGER_REFERENCE = 25;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTEGER_REFERENCE__VALUE = ATOMIC_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Integer Reference</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTEGER_REFERENCE_FEATURE_COUNT = ATOMIC_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.DoubleReferenceImpl <em>Double Reference</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.DoubleReferenceImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDoubleReference()
   * @generated
   */
  int DOUBLE_REFERENCE = 26;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOUBLE_REFERENCE__VALUE = ATOMIC_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Double Reference</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOUBLE_REFERENCE_FEATURE_COUNT = ATOMIC_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.StringReferenceImpl <em>String Reference</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.StringReferenceImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getStringReference()
   * @generated
   */
  int STRING_REFERENCE = 27;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_REFERENCE__VALUE = ATOMIC_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>String Reference</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_REFERENCE_FEATURE_COUNT = ATOMIC_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.BooleanReferenceImpl <em>Boolean Reference</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.BooleanReferenceImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getBooleanReference()
   * @generated
   */
  int BOOLEAN_REFERENCE = 28;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_REFERENCE__VALUE = ATOMIC_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Boolean Reference</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_REFERENCE_FEATURE_COUNT = ATOMIC_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ArrayReferenceImpl <em>Array Reference</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ArrayReferenceImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getArrayReference()
   * @generated
   */
  int ARRAY_REFERENCE = 29;

  /**
   * The feature id for the '<em><b>Variable Reference</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_REFERENCE__VARIABLE_REFERENCE = ATOMIC_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Dimension</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_REFERENCE__DIMENSION = ATOMIC_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Array Reference</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_REFERENCE_FEATURE_COUNT = ATOMIC_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.VariableReferenceImpl <em>Variable Reference</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.VariableReferenceImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getVariableReference()
   * @generated
   */
  int VARIABLE_REFERENCE = 30;

  /**
   * The feature id for the '<em><b>Variable Reference</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_REFERENCE__VARIABLE_REFERENCE = ATOMIC_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Variable Reference</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_REFERENCE_FEATURE_COUNT = ATOMIC_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.InkApp <em>Ink App</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ink App</em>'.
   * @see org.xtext.example.mydsl.myDsl.InkApp
   * @generated
   */
  EClass getInkApp();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.InkApp#getGlobals <em>Globals</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Globals</em>'.
   * @see org.xtext.example.mydsl.myDsl.InkApp#getGlobals()
   * @see #getInkApp()
   * @generated
   */
  EReference getInkApp_Globals();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.InkApp#getTasks <em>Tasks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tasks</em>'.
   * @see org.xtext.example.mydsl.myDsl.InkApp#getTasks()
   * @see #getInkApp()
   * @generated
   */
  EReference getInkApp_Tasks();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.InkApp#getEntry <em>Entry</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Entry</em>'.
   * @see org.xtext.example.mydsl.myDsl.InkApp#getEntry()
   * @see #getInkApp()
   * @generated
   */
  EReference getInkApp_Entry();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Break <em>Break</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Break</em>'.
   * @see org.xtext.example.mydsl.myDsl.Break
   * @generated
   */
  EClass getBreak();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Break#getBreak <em>Break</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Break</em>'.
   * @see org.xtext.example.mydsl.myDsl.Break#getBreak()
   * @see #getBreak()
   * @generated
   */
  EAttribute getBreak_Break();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.VariableType <em>Variable Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable Type</em>'.
   * @see org.xtext.example.mydsl.myDsl.VariableType
   * @generated
   */
  EClass getVariableType();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.GlobalVariable <em>Global Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Global Variable</em>'.
   * @see org.xtext.example.mydsl.myDsl.GlobalVariable
   * @generated
   */
  EClass getGlobalVariable();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.GlobalVariable#getVariable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Variable</em>'.
   * @see org.xtext.example.mydsl.myDsl.GlobalVariable#getVariable()
   * @see #getGlobalVariable()
   * @generated
   */
  EReference getGlobalVariable_Variable();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Main <em>Main</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Main</em>'.
   * @see org.xtext.example.mydsl.myDsl.Main
   * @generated
   */
  EClass getMain();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Main#getVariableDeclerations <em>Variable Declerations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Variable Declerations</em>'.
   * @see org.xtext.example.mydsl.myDsl.Main#getVariableDeclerations()
   * @see #getMain()
   * @generated
   */
  EReference getMain_VariableDeclerations();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Main#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Body</em>'.
   * @see org.xtext.example.mydsl.myDsl.Main#getBody()
   * @see #getMain()
   * @generated
   */
  EReference getMain_Body();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.FunctionBody <em>Function Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function Body</em>'.
   * @see org.xtext.example.mydsl.myDsl.FunctionBody
   * @generated
   */
  EClass getFunctionBody();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.FunctionBody#getVariableDeclerations <em>Variable Declerations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Variable Declerations</em>'.
   * @see org.xtext.example.mydsl.myDsl.FunctionBody#getVariableDeclerations()
   * @see #getFunctionBody()
   * @generated
   */
  EReference getFunctionBody_VariableDeclerations();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.FunctionBody#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Body</em>'.
   * @see org.xtext.example.mydsl.myDsl.FunctionBody#getBody()
   * @see #getFunctionBody()
   * @generated
   */
  EReference getFunctionBody_Body();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.EntryTask <em>Entry Task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entry Task</em>'.
   * @see org.xtext.example.mydsl.myDsl.EntryTask
   * @generated
   */
  EClass getEntryTask();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.EntryTask#getTask <em>Task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Task</em>'.
   * @see org.xtext.example.mydsl.myDsl.EntryTask#getTask()
   * @see #getEntryTask()
   * @generated
   */
  EReference getEntryTask_Task();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Task <em>Task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Task</em>'.
   * @see org.xtext.example.mydsl.myDsl.Task
   * @generated
   */
  EClass getTask();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Task#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Task#getName()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Task#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Body</em>'.
   * @see org.xtext.example.mydsl.myDsl.Task#getBody()
   * @see #getTask()
   * @generated
   */
  EReference getTask_Body();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.myDsl.Task#getTask <em>Task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Task</em>'.
   * @see org.xtext.example.mydsl.myDsl.Task#getTask()
   * @see #getTask()
   * @generated
   */
  EReference getTask_Task();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.IfExpression <em>If Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>If Expression</em>'.
   * @see org.xtext.example.mydsl.myDsl.IfExpression
   * @generated
   */
  EClass getIfExpression();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.IfExpression#getIfcondition <em>Ifcondition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ifcondition</em>'.
   * @see org.xtext.example.mydsl.myDsl.IfExpression#getIfcondition()
   * @see #getIfExpression()
   * @generated
   */
  EReference getIfExpression_Ifcondition();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.IfExpression#getIfbody <em>Ifbody</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Ifbody</em>'.
   * @see org.xtext.example.mydsl.myDsl.IfExpression#getIfbody()
   * @see #getIfExpression()
   * @generated
   */
  EReference getIfExpression_Ifbody();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.IfExpression#getElsecondition <em>Elsecondition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elsecondition</em>'.
   * @see org.xtext.example.mydsl.myDsl.IfExpression#getElsecondition()
   * @see #getIfExpression()
   * @generated
   */
  EReference getIfExpression_Elsecondition();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.IfExpression#getElseifbody <em>Elseifbody</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elseifbody</em>'.
   * @see org.xtext.example.mydsl.myDsl.IfExpression#getElseifbody()
   * @see #getIfExpression()
   * @generated
   */
  EReference getIfExpression_Elseifbody();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.IfExpression#getElsebody <em>Elsebody</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elsebody</em>'.
   * @see org.xtext.example.mydsl.myDsl.IfExpression#getElsebody()
   * @see #getIfExpression()
   * @generated
   */
  EReference getIfExpression_Elsebody();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.ForExpression <em>For Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>For Expression</em>'.
   * @see org.xtext.example.mydsl.myDsl.ForExpression
   * @generated
   */
  EClass getForExpression();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.ForExpression#getInitial <em>Initial</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Initial</em>'.
   * @see org.xtext.example.mydsl.myDsl.ForExpression#getInitial()
   * @see #getForExpression()
   * @generated
   */
  EReference getForExpression_Initial();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.ForExpression#getTest <em>Test</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Test</em>'.
   * @see org.xtext.example.mydsl.myDsl.ForExpression#getTest()
   * @see #getForExpression()
   * @generated
   */
  EReference getForExpression_Test();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.ForExpression#getUpdate <em>Update</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Update</em>'.
   * @see org.xtext.example.mydsl.myDsl.ForExpression#getUpdate()
   * @see #getForExpression()
   * @generated
   */
  EReference getForExpression_Update();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.ForExpression#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Body</em>'.
   * @see org.xtext.example.mydsl.myDsl.ForExpression#getBody()
   * @see #getForExpression()
   * @generated
   */
  EReference getForExpression_Body();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.WhileExpression <em>While Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>While Expression</em>'.
   * @see org.xtext.example.mydsl.myDsl.WhileExpression
   * @generated
   */
  EClass getWhileExpression();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.WhileExpression#getTest <em>Test</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Test</em>'.
   * @see org.xtext.example.mydsl.myDsl.WhileExpression#getTest()
   * @see #getWhileExpression()
   * @generated
   */
  EReference getWhileExpression_Test();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.WhileExpression#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Body</em>'.
   * @see org.xtext.example.mydsl.myDsl.WhileExpression#getBody()
   * @see #getWhileExpression()
   * @generated
   */
  EReference getWhileExpression_Body();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see org.xtext.example.mydsl.myDsl.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.OperationExpression <em>Operation Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operation Expression</em>'.
   * @see org.xtext.example.mydsl.myDsl.OperationExpression
   * @generated
   */
  EClass getOperationExpression();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.ArrayDimension <em>Array Dimension</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Array Dimension</em>'.
   * @see org.xtext.example.mydsl.myDsl.ArrayDimension
   * @generated
   */
  EClass getArrayDimension();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.myDsl.ArrayDimension#getIndex <em>Index</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Index</em>'.
   * @see org.xtext.example.mydsl.myDsl.ArrayDimension#getIndex()
   * @see #getArrayDimension()
   * @generated
   */
  EReference getArrayDimension_Index();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.ArrayDimension#getSize <em>Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Size</em>'.
   * @see org.xtext.example.mydsl.myDsl.ArrayDimension#getSize()
   * @see #getArrayDimension()
   * @generated
   */
  EAttribute getArrayDimension_Size();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.VariableDecleration <em>Variable Decleration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable Decleration</em>'.
   * @see org.xtext.example.mydsl.myDsl.VariableDecleration
   * @generated
   */
  EClass getVariableDecleration();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.VariableDecleration#getDimension <em>Dimension</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Dimension</em>'.
   * @see org.xtext.example.mydsl.myDsl.VariableDecleration#getDimension()
   * @see #getVariableDecleration()
   * @generated
   */
  EReference getVariableDecleration_Dimension();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.FunctionParameter <em>Function Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function Parameter</em>'.
   * @see org.xtext.example.mydsl.myDsl.FunctionParameter
   * @generated
   */
  EClass getFunctionParameter();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.VariableSymbol <em>Variable Symbol</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable Symbol</em>'.
   * @see org.xtext.example.mydsl.myDsl.VariableSymbol
   * @generated
   */
  EClass getVariableSymbol();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.VariableSymbol#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see org.xtext.example.mydsl.myDsl.VariableSymbol#getType()
   * @see #getVariableSymbol()
   * @generated
   */
  EReference getVariableSymbol_Type();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.VariableSymbol#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.VariableSymbol#getName()
   * @see #getVariableSymbol()
   * @generated
   */
  EAttribute getVariableSymbol_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Atomic <em>Atomic</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Atomic</em>'.
   * @see org.xtext.example.mydsl.myDsl.Atomic
   * @generated
   */
  EClass getAtomic();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.VariableReturn <em>Variable Return</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable Return</em>'.
   * @see org.xtext.example.mydsl.myDsl.VariableReturn
   * @generated
   */
  EClass getVariableReturn();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.VariableReturn#getReturn <em>Return</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Return</em>'.
   * @see org.xtext.example.mydsl.myDsl.VariableReturn#getReturn()
   * @see #getVariableReturn()
   * @generated
   */
  EReference getVariableReturn_Return();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.AtomicOrFunctionCall <em>Atomic Or Function Call</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Atomic Or Function Call</em>'.
   * @see org.xtext.example.mydsl.myDsl.AtomicOrFunctionCall
   * @generated
   */
  EClass getAtomicOrFunctionCall();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.FunctionDefinition <em>Function Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function Definition</em>'.
   * @see org.xtext.example.mydsl.myDsl.FunctionDefinition
   * @generated
   */
  EClass getFunctionDefinition();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.FunctionDefinition#getReturn <em>Return</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Return</em>'.
   * @see org.xtext.example.mydsl.myDsl.FunctionDefinition#getReturn()
   * @see #getFunctionDefinition()
   * @generated
   */
  EReference getFunctionDefinition_Return();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.FunctionDefinition#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.FunctionDefinition#getName()
   * @see #getFunctionDefinition()
   * @generated
   */
  EAttribute getFunctionDefinition_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.FunctionDefinition#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parameters</em>'.
   * @see org.xtext.example.mydsl.myDsl.FunctionDefinition#getParameters()
   * @see #getFunctionDefinition()
   * @generated
   */
  EReference getFunctionDefinition_Parameters();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.FunctionDefinition#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Body</em>'.
   * @see org.xtext.example.mydsl.myDsl.FunctionDefinition#getBody()
   * @see #getFunctionDefinition()
   * @generated
   */
  EReference getFunctionDefinition_Body();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.FunctionCall <em>Function Call</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function Call</em>'.
   * @see org.xtext.example.mydsl.myDsl.FunctionCall
   * @generated
   */
  EClass getFunctionCall();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.myDsl.FunctionCall#getFunction <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Function</em>'.
   * @see org.xtext.example.mydsl.myDsl.FunctionCall#getFunction()
   * @see #getFunctionCall()
   * @generated
   */
  EReference getFunctionCall_Function();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.BuiltinFunctionCall <em>Builtin Function Call</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Builtin Function Call</em>'.
   * @see org.xtext.example.mydsl.myDsl.BuiltinFunctionCall
   * @generated
   */
  EClass getBuiltinFunctionCall();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.BuiltinFunctionCall#getFunction <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Function</em>'.
   * @see org.xtext.example.mydsl.myDsl.BuiltinFunctionCall#getFunction()
   * @see #getBuiltinFunctionCall()
   * @generated
   */
  EAttribute getBuiltinFunctionCall_Function();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.AbstractFunctionCall <em>Abstract Function Call</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Abstract Function Call</em>'.
   * @see org.xtext.example.mydsl.myDsl.AbstractFunctionCall
   * @generated
   */
  EClass getAbstractFunctionCall();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.AbstractFunctionCall#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parameters</em>'.
   * @see org.xtext.example.mydsl.myDsl.AbstractFunctionCall#getParameters()
   * @see #getAbstractFunctionCall()
   * @generated
   */
  EReference getAbstractFunctionCall_Parameters();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Operation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operation</em>'.
   * @see org.xtext.example.mydsl.myDsl.Operation
   * @generated
   */
  EClass getOperation();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Operation#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.xtext.example.mydsl.myDsl.Operation#getLeft()
   * @see #getOperation()
   * @generated
   */
  EReference getOperation_Left();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl.myDsl.Operation#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Operator</em>'.
   * @see org.xtext.example.mydsl.myDsl.Operation#getOperator()
   * @see #getOperation()
   * @generated
   */
  EAttribute getOperation_Operator();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Operation#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Right</em>'.
   * @see org.xtext.example.mydsl.myDsl.Operation#getRight()
   * @see #getOperation()
   * @generated
   */
  EReference getOperation_Right();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.IntegerReference <em>Integer Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Integer Reference</em>'.
   * @see org.xtext.example.mydsl.myDsl.IntegerReference
   * @generated
   */
  EClass getIntegerReference();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.IntegerReference#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.mydsl.myDsl.IntegerReference#getValue()
   * @see #getIntegerReference()
   * @generated
   */
  EAttribute getIntegerReference_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.DoubleReference <em>Double Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Double Reference</em>'.
   * @see org.xtext.example.mydsl.myDsl.DoubleReference
   * @generated
   */
  EClass getDoubleReference();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.DoubleReference#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.mydsl.myDsl.DoubleReference#getValue()
   * @see #getDoubleReference()
   * @generated
   */
  EAttribute getDoubleReference_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.StringReference <em>String Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Reference</em>'.
   * @see org.xtext.example.mydsl.myDsl.StringReference
   * @generated
   */
  EClass getStringReference();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.StringReference#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.mydsl.myDsl.StringReference#getValue()
   * @see #getStringReference()
   * @generated
   */
  EAttribute getStringReference_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.BooleanReference <em>Boolean Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Boolean Reference</em>'.
   * @see org.xtext.example.mydsl.myDsl.BooleanReference
   * @generated
   */
  EClass getBooleanReference();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.BooleanReference#isValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.mydsl.myDsl.BooleanReference#isValue()
   * @see #getBooleanReference()
   * @generated
   */
  EAttribute getBooleanReference_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.ArrayReference <em>Array Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Array Reference</em>'.
   * @see org.xtext.example.mydsl.myDsl.ArrayReference
   * @generated
   */
  EClass getArrayReference();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.myDsl.ArrayReference#getVariableReference <em>Variable Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Variable Reference</em>'.
   * @see org.xtext.example.mydsl.myDsl.ArrayReference#getVariableReference()
   * @see #getArrayReference()
   * @generated
   */
  EReference getArrayReference_VariableReference();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.ArrayReference#getDimension <em>Dimension</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Dimension</em>'.
   * @see org.xtext.example.mydsl.myDsl.ArrayReference#getDimension()
   * @see #getArrayReference()
   * @generated
   */
  EReference getArrayReference_Dimension();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.VariableReference <em>Variable Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable Reference</em>'.
   * @see org.xtext.example.mydsl.myDsl.VariableReference
   * @generated
   */
  EClass getVariableReference();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.myDsl.VariableReference#getVariableReference <em>Variable Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Variable Reference</em>'.
   * @see org.xtext.example.mydsl.myDsl.VariableReference#getVariableReference()
   * @see #getVariableReference()
   * @generated
   */
  EReference getVariableReference_VariableReference();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.InkAppImpl <em>Ink App</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.InkAppImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getInkApp()
     * @generated
     */
    EClass INK_APP = eINSTANCE.getInkApp();

    /**
     * The meta object literal for the '<em><b>Globals</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INK_APP__GLOBALS = eINSTANCE.getInkApp_Globals();

    /**
     * The meta object literal for the '<em><b>Tasks</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INK_APP__TASKS = eINSTANCE.getInkApp_Tasks();

    /**
     * The meta object literal for the '<em><b>Entry</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INK_APP__ENTRY = eINSTANCE.getInkApp_Entry();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.BreakImpl <em>Break</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.BreakImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getBreak()
     * @generated
     */
    EClass BREAK = eINSTANCE.getBreak();

    /**
     * The meta object literal for the '<em><b>Break</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BREAK__BREAK = eINSTANCE.getBreak_Break();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.VariableTypeImpl <em>Variable Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.VariableTypeImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getVariableType()
     * @generated
     */
    EClass VARIABLE_TYPE = eINSTANCE.getVariableType();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.GlobalVariableImpl <em>Global Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.GlobalVariableImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getGlobalVariable()
     * @generated
     */
    EClass GLOBAL_VARIABLE = eINSTANCE.getGlobalVariable();

    /**
     * The meta object literal for the '<em><b>Variable</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GLOBAL_VARIABLE__VARIABLE = eINSTANCE.getGlobalVariable_Variable();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.MainImpl <em>Main</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.MainImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getMain()
     * @generated
     */
    EClass MAIN = eINSTANCE.getMain();

    /**
     * The meta object literal for the '<em><b>Variable Declerations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAIN__VARIABLE_DECLERATIONS = eINSTANCE.getMain_VariableDeclerations();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAIN__BODY = eINSTANCE.getMain_Body();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.FunctionBodyImpl <em>Function Body</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.FunctionBodyImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFunctionBody()
     * @generated
     */
    EClass FUNCTION_BODY = eINSTANCE.getFunctionBody();

    /**
     * The meta object literal for the '<em><b>Variable Declerations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION_BODY__VARIABLE_DECLERATIONS = eINSTANCE.getFunctionBody_VariableDeclerations();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION_BODY__BODY = eINSTANCE.getFunctionBody_Body();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.EntryTaskImpl <em>Entry Task</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.EntryTaskImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getEntryTask()
     * @generated
     */
    EClass ENTRY_TASK = eINSTANCE.getEntryTask();

    /**
     * The meta object literal for the '<em><b>Task</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTRY_TASK__TASK = eINSTANCE.getEntryTask_Task();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.TaskImpl <em>Task</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.TaskImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getTask()
     * @generated
     */
    EClass TASK = eINSTANCE.getTask();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__NAME = eINSTANCE.getTask_Name();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK__BODY = eINSTANCE.getTask_Body();

    /**
     * The meta object literal for the '<em><b>Task</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK__TASK = eINSTANCE.getTask_Task();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.IfExpressionImpl <em>If Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.IfExpressionImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getIfExpression()
     * @generated
     */
    EClass IF_EXPRESSION = eINSTANCE.getIfExpression();

    /**
     * The meta object literal for the '<em><b>Ifcondition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_EXPRESSION__IFCONDITION = eINSTANCE.getIfExpression_Ifcondition();

    /**
     * The meta object literal for the '<em><b>Ifbody</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_EXPRESSION__IFBODY = eINSTANCE.getIfExpression_Ifbody();

    /**
     * The meta object literal for the '<em><b>Elsecondition</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_EXPRESSION__ELSECONDITION = eINSTANCE.getIfExpression_Elsecondition();

    /**
     * The meta object literal for the '<em><b>Elseifbody</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_EXPRESSION__ELSEIFBODY = eINSTANCE.getIfExpression_Elseifbody();

    /**
     * The meta object literal for the '<em><b>Elsebody</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_EXPRESSION__ELSEBODY = eINSTANCE.getIfExpression_Elsebody();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ForExpressionImpl <em>For Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ForExpressionImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getForExpression()
     * @generated
     */
    EClass FOR_EXPRESSION = eINSTANCE.getForExpression();

    /**
     * The meta object literal for the '<em><b>Initial</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR_EXPRESSION__INITIAL = eINSTANCE.getForExpression_Initial();

    /**
     * The meta object literal for the '<em><b>Test</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR_EXPRESSION__TEST = eINSTANCE.getForExpression_Test();

    /**
     * The meta object literal for the '<em><b>Update</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR_EXPRESSION__UPDATE = eINSTANCE.getForExpression_Update();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR_EXPRESSION__BODY = eINSTANCE.getForExpression_Body();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.WhileExpressionImpl <em>While Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.WhileExpressionImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getWhileExpression()
     * @generated
     */
    EClass WHILE_EXPRESSION = eINSTANCE.getWhileExpression();

    /**
     * The meta object literal for the '<em><b>Test</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHILE_EXPRESSION__TEST = eINSTANCE.getWhileExpression_Test();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHILE_EXPRESSION__BODY = eINSTANCE.getWhileExpression_Body();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ExpressionImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.OperationExpressionImpl <em>Operation Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.OperationExpressionImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getOperationExpression()
     * @generated
     */
    EClass OPERATION_EXPRESSION = eINSTANCE.getOperationExpression();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ArrayDimensionImpl <em>Array Dimension</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ArrayDimensionImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getArrayDimension()
     * @generated
     */
    EClass ARRAY_DIMENSION = eINSTANCE.getArrayDimension();

    /**
     * The meta object literal for the '<em><b>Index</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARRAY_DIMENSION__INDEX = eINSTANCE.getArrayDimension_Index();

    /**
     * The meta object literal for the '<em><b>Size</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARRAY_DIMENSION__SIZE = eINSTANCE.getArrayDimension_Size();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.VariableDeclerationImpl <em>Variable Decleration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.VariableDeclerationImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getVariableDecleration()
     * @generated
     */
    EClass VARIABLE_DECLERATION = eINSTANCE.getVariableDecleration();

    /**
     * The meta object literal for the '<em><b>Dimension</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIABLE_DECLERATION__DIMENSION = eINSTANCE.getVariableDecleration_Dimension();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.FunctionParameterImpl <em>Function Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.FunctionParameterImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFunctionParameter()
     * @generated
     */
    EClass FUNCTION_PARAMETER = eINSTANCE.getFunctionParameter();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.VariableSymbolImpl <em>Variable Symbol</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.VariableSymbolImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getVariableSymbol()
     * @generated
     */
    EClass VARIABLE_SYMBOL = eINSTANCE.getVariableSymbol();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIABLE_SYMBOL__TYPE = eINSTANCE.getVariableSymbol_Type();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_SYMBOL__NAME = eINSTANCE.getVariableSymbol_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.AtomicImpl <em>Atomic</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.AtomicImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAtomic()
     * @generated
     */
    EClass ATOMIC = eINSTANCE.getAtomic();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.VariableReturnImpl <em>Variable Return</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.VariableReturnImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getVariableReturn()
     * @generated
     */
    EClass VARIABLE_RETURN = eINSTANCE.getVariableReturn();

    /**
     * The meta object literal for the '<em><b>Return</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIABLE_RETURN__RETURN = eINSTANCE.getVariableReturn_Return();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.AtomicOrFunctionCallImpl <em>Atomic Or Function Call</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.AtomicOrFunctionCallImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAtomicOrFunctionCall()
     * @generated
     */
    EClass ATOMIC_OR_FUNCTION_CALL = eINSTANCE.getAtomicOrFunctionCall();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.FunctionDefinitionImpl <em>Function Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.FunctionDefinitionImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFunctionDefinition()
     * @generated
     */
    EClass FUNCTION_DEFINITION = eINSTANCE.getFunctionDefinition();

    /**
     * The meta object literal for the '<em><b>Return</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION_DEFINITION__RETURN = eINSTANCE.getFunctionDefinition_Return();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCTION_DEFINITION__NAME = eINSTANCE.getFunctionDefinition_Name();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION_DEFINITION__PARAMETERS = eINSTANCE.getFunctionDefinition_Parameters();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION_DEFINITION__BODY = eINSTANCE.getFunctionDefinition_Body();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.FunctionCallImpl <em>Function Call</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.FunctionCallImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFunctionCall()
     * @generated
     */
    EClass FUNCTION_CALL = eINSTANCE.getFunctionCall();

    /**
     * The meta object literal for the '<em><b>Function</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION_CALL__FUNCTION = eINSTANCE.getFunctionCall_Function();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.BuiltinFunctionCallImpl <em>Builtin Function Call</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.BuiltinFunctionCallImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getBuiltinFunctionCall()
     * @generated
     */
    EClass BUILTIN_FUNCTION_CALL = eINSTANCE.getBuiltinFunctionCall();

    /**
     * The meta object literal for the '<em><b>Function</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BUILTIN_FUNCTION_CALL__FUNCTION = eINSTANCE.getBuiltinFunctionCall_Function();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.AbstractFunctionCallImpl <em>Abstract Function Call</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.AbstractFunctionCallImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAbstractFunctionCall()
     * @generated
     */
    EClass ABSTRACT_FUNCTION_CALL = eINSTANCE.getAbstractFunctionCall();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ABSTRACT_FUNCTION_CALL__PARAMETERS = eINSTANCE.getAbstractFunctionCall_Parameters();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.OperationImpl <em>Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.OperationImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getOperation()
     * @generated
     */
    EClass OPERATION = eINSTANCE.getOperation();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPERATION__LEFT = eINSTANCE.getOperation_Left();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERATION__OPERATOR = eINSTANCE.getOperation_Operator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPERATION__RIGHT = eINSTANCE.getOperation_Right();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.IntegerReferenceImpl <em>Integer Reference</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.IntegerReferenceImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getIntegerReference()
     * @generated
     */
    EClass INTEGER_REFERENCE = eINSTANCE.getIntegerReference();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INTEGER_REFERENCE__VALUE = eINSTANCE.getIntegerReference_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.DoubleReferenceImpl <em>Double Reference</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.DoubleReferenceImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDoubleReference()
     * @generated
     */
    EClass DOUBLE_REFERENCE = eINSTANCE.getDoubleReference();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DOUBLE_REFERENCE__VALUE = eINSTANCE.getDoubleReference_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.StringReferenceImpl <em>String Reference</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.StringReferenceImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getStringReference()
     * @generated
     */
    EClass STRING_REFERENCE = eINSTANCE.getStringReference();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_REFERENCE__VALUE = eINSTANCE.getStringReference_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.BooleanReferenceImpl <em>Boolean Reference</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.BooleanReferenceImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getBooleanReference()
     * @generated
     */
    EClass BOOLEAN_REFERENCE = eINSTANCE.getBooleanReference();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOLEAN_REFERENCE__VALUE = eINSTANCE.getBooleanReference_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ArrayReferenceImpl <em>Array Reference</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ArrayReferenceImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getArrayReference()
     * @generated
     */
    EClass ARRAY_REFERENCE = eINSTANCE.getArrayReference();

    /**
     * The meta object literal for the '<em><b>Variable Reference</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARRAY_REFERENCE__VARIABLE_REFERENCE = eINSTANCE.getArrayReference_VariableReference();

    /**
     * The meta object literal for the '<em><b>Dimension</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARRAY_REFERENCE__DIMENSION = eINSTANCE.getArrayReference_Dimension();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.VariableReferenceImpl <em>Variable Reference</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.VariableReferenceImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getVariableReference()
     * @generated
     */
    EClass VARIABLE_REFERENCE = eINSTANCE.getVariableReference();

    /**
     * The meta object literal for the '<em><b>Variable Reference</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIABLE_REFERENCE__VARIABLE_REFERENCE = eINSTANCE.getVariableReference_VariableReference();

  }

} //MyDslPackage
