/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Task Body</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.TaskBody#getBody <em>Body</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.TaskBody#getNexttask <em>Nexttask</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.TaskBody#getEndtask <em>Endtask</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTaskBody()
 * @model
 * @generated
 */
public interface TaskBody extends EObject
{
  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.emf.ecore.EObject}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTaskBody_Body()
   * @model containment="true"
   * @generated
   */
  EList<EObject> getBody();

  /**
   * Returns the value of the '<em><b>Nexttask</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nexttask</em>' reference.
   * @see #setNexttask(Task)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTaskBody_Nexttask()
   * @model
   * @generated
   */
  Task getNexttask();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.TaskBody#getNexttask <em>Nexttask</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nexttask</em>' reference.
   * @see #getNexttask()
   * @generated
   */
  void setNexttask(Task value);

  /**
   * Returns the value of the '<em><b>Endtask</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Endtask</em>' attribute.
   * @see #setEndtask(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTaskBody_Endtask()
   * @model
   * @generated
   */
  String getEndtask();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.TaskBody#getEndtask <em>Endtask</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Endtask</em>' attribute.
   * @see #getEndtask()
   * @generated
   */
  void setEndtask(String value);

} // TaskBody
