/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>While Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.WhileExpression#getTest <em>Test</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.WhileExpression#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getWhileExpression()
 * @model
 * @generated
 */
public interface WhileExpression extends BlockExpressions, Expression
{
  /**
   * Returns the value of the '<em><b>Test</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Test</em>' containment reference.
   * @see #setTest(OperationExpression)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getWhileExpression_Test()
   * @model containment="true"
   * @generated
   */
  OperationExpression getTest();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.WhileExpression#getTest <em>Test</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Test</em>' containment reference.
   * @see #getTest()
   * @generated
   */
  void setTest(OperationExpression value);

  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference.
   * @see #setBody(StatementBody)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getWhileExpression_Body()
   * @model containment="true"
   * @generated
   */
  StatementBody getBody();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.WhileExpression#getBody <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' containment reference.
   * @see #getBody()
   * @generated
   */
  void setBody(StatementBody value);

} // WhileExpression
